### ISSUE TITLE
Demo content disappeared

### ISSUE THREAD

**Issue by rollecode** [digitoimistodude/air-light-demo-content#1]
I guess this plugin need refining after changes in 7.5.0? @timiwahalahti 

![Screen-Shot-2021-05-21-15-14-34 30](https://user-images.githubusercontent.com/1534150/119135571-46e83700-ba47-11eb-9c0f-2b10409301cf.png)

**Comment by timiwahalahti** [comment]
Fixed in https://github.com/digitoimistodude/air-light-demo-content/commit/69f68123d8fd57ecf54e75ec9e443f7ee2703bb1
